//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbuReservationSystem.Web.App_GlobalResources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NbuReservationSystem.Web.App_GlobalResources.Home.AboutContent", typeof(AboutContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проектът е разработен в рамките на Задание, предоставено от екипа на Нов Български университет по името „Система за резервиране на залите в библиотеката на НБУ“..
        /// </summary>
        public static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целта на проекта е да позволи автоматизацията на процеса по резервиране на времеви интервали в залите в НБУ..
        /// </summary>
        public static string AboutProject1 {
            get {
                return ResourceManager.GetString("AboutProject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преди стартиране на проекта, инструмента, който е ползван е частично автоматизиран, изисква високо ниво на ръчен труд при управление и администриране и също така се основава на външни ИТ решения за НБУ..
        /// </summary>
        public static string AboutProject2 {
            get {
                return ResourceManager.GetString("AboutProject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С помощта на CARL ние се надяваме да допринесем за резолирането на тези проблеми..
        /// </summary>
        public static string AboutProject3 {
            get {
                return ResourceManager.GetString("AboutProject3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ние сме екип, който цели да изпълнява реални проекти, да развива и оптимизира.
        ///
        ///Екипът се състои от:.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашата скромна дружинка представя нашият мастър на заявките – CARL..
        /// </summary>
        public static string AboutusBottom {
            get {
                return ResourceManager.GetString("AboutusBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кирил Бадаланов – Господин „Според спецификацията…“ или Бизнес Анализатор.
        /// </summary>
        public static string AboutUsKiril {
            get {
                return ResourceManager.GetString("AboutUsKiril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Николай Ангелов – Господин „Постоянен качествен контрол“ или QA.
        /// </summary>
        public static string AboutUsNikolay {
            get {
                return ResourceManager.GetString("AboutUsNikolay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цветан Стоянов – Господин „Аз съм много амбициозен“ или Junior Dev.
        /// </summary>
        public static string AboutUsTsvetan {
            get {
                return ResourceManager.GetString("AboutUsTsvetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Венеция Нецова – Госпожица „Нека да направим екселски файл“ или Project Manager.
        /// </summary>
        public static string AboutUsVenetsiya {
            get {
                return ResourceManager.GetString("AboutUsVenetsiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виктор Василев – Господин „Знам си всичко аз“ или по-старши Junior Dev.
        /// </summary>
        public static string AboutUsViktor {
            get {
                return ResourceManager.GetString("AboutUsViktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тук.
        /// </summary>
        public static string AdminLink {
            get {
                return ResourceManager.GetString("AdminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайтът може да се администрира от.
        /// </summary>
        public static string AdminTxt {
            get {
                return ResourceManager.GetString("AdminTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За проекта.
        /// </summary>
        public static string TitleAboutProject {
            get {
                return ResourceManager.GetString("TitleAboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string TitleAboutUs {
            get {
                return ResourceManager.GetString("TitleAboutUs", resourceCulture);
            }
        }
    }
}
