//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbuReservationSystem.Web.App_GlobalResources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NbuReservationSystem.Web.App_GlobalResources.Home.IndexContent", typeof(IndexContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервирайте първи.
        /// </summary>
        public static string BeTheFirstToMakeReservation {
            get {
                return ResourceManager.GetString("BeTheFirstToMakeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени своята резервация.
        /// </summary>
        public static string ChangeReservation {
            get {
                return ResourceManager.GetString("ChangeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете да промените резервация като използвате кода, получен при създаване на Вашето събитие..
        /// </summary>
        public static string ChangeReservationTxt {
            get {
                return ResourceManager.GetString("ChangeReservationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпвайте системата през своя лаптоп, телефон или таблет.
        /// </summary>
        public static string PcAndMobileSupport {
            get {
                return ResourceManager.GetString("PcAndMobileSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте навреме бъдещи събития.
        /// </summary>
        public static string PlanEvents {
            get {
                return ResourceManager.GetString("PlanEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прегледай резервациите по дни и месеци.
        /// </summary>
        public static string PreviewDayAndMonth {
            get {
                return ResourceManager.GetString("PreviewDayAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да планирате по-добре бъдещите Ви ангажименти, можете да прегледате планираните резервации по дни и месеци..
        /// </summary>
        public static string PreviewDayAndMonthTxt {
            get {
                return ResourceManager.GetString("PreviewDayAndMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получи ли нашето потвърждение?.
        /// </summary>
        public static string ReceiveOurConfirmation {
            get {
                return ResourceManager.GetString("ReceiveOurConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да сте сигурни, че успешно сте създали Вашата резервация – CARL ще ви изпрати e-mail с детайлите на Вашето събитие. В допълнение – можете да видите новосъздаденото събитие в самия календар в избраната от Вас дата..
        /// </summary>
        public static string ReceiveOurConfirmationTxt {
            get {
                return ResourceManager.GetString("ReceiveOurConfirmationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервирай зала бързо и лесно.
        /// </summary>
        public static string RegisterFastAndEasy {
            get {
                return ResourceManager.GetString("RegisterFastAndEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервирай сега в няколко лесни стъпки своите събития. CARL ще ти помогне като ти предостави възможност автоматично да заложиш регулярна повторяемост – да, не е необходимо да въвеждаш всеки път..
        /// </summary>
        public static string RegisterFastAndEasyTxt {
            get {
                return ResourceManager.GetString("RegisterFastAndEasyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едно място за всички резервации за зали.
        /// </summary>
        public static string ReservationHalls {
            get {
                return ResourceManager.GetString("ReservationHalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информирайте се какви други събития се провеждат.
        /// </summary>
        public static string StayInformed {
            get {
                return ResourceManager.GetString("StayInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защо да се доверите на CARL.
        /// </summary>
        public static string WhyCARL {
            get {
                return ResourceManager.GetString("WhyCARL", resourceCulture);
            }
        }
    }
}
