//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbuReservationSystem.Web.App_GlobalResources.Labels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReservationLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReservationLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NbuReservationSystem.Web.App_GlobalResources.Labels.ReservationLabels", typeof(ReservationLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложи промените за всички инстанции на това събитие?.
        /// </summary>
        public static string ApplyToWholeSeries {
            get {
                return ResourceManager.GetString("ApplyToWholeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възложител.
        /// </summary>
        public static string Assignor {
            get {
                return ResourceManager.GetString("Assignor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начален час.
        /// </summary>
        public static string BeginsOn {
            get {
                return ResourceManager.GetString("BeginsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчисти.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий резервацията/йте/?.
        /// </summary>
        public static string DeleteReservations {
            get {
                return ResourceManager.GetString("DeleteReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-майл.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краен час.
        /// </summary>
        public static string EndsOn {
            get {
                return ResourceManager.GetString("EndsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завинаги.
        /// </summary>
        public static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зала.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужна ли е мултимедийна / озвучителна техника?.
        /// </summary>
        public static string IsEquipmentRequired {
            get {
                return ResourceManager.GetString("IsEquipmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes are saved..
        /// </summary>
        public static string ModifyRequestSuccess {
            get {
                return ResourceManager.GetString("ModifyRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to резервации.
        /// </summary>
        public static string MultipleReservations {
            get {
                return ResourceManager.GetString("MultipleReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова резервация.
        /// </summary>
        public static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма добавени зали. Моля свържете се с администратора..
        /// </summary>
        public static string NoHalls {
            get {
                return ResourceManager.GetString("NoHalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма направени резервации..
        /// </summary>
        public static string NoReservations {
            get {
                return ResourceManager.GetString("NoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еднократно.
        /// </summary>
        public static string OneTimeOnly {
            get {
                return ResourceManager.GetString("OneTimeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лице за контакт.
        /// </summary>
        public static string PointOfContact {
            get {
                return ResourceManager.GetString("PointOfContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтаряемост.
        /// </summary>
        public static string RepetitionPolicy {
            get {
                return ResourceManager.GetString("RepetitionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След брой повторения.
        /// </summary>
        public static string RepetitionsCount {
            get {
                return ResourceManager.GetString("RepetitionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to През колко седмици.
        /// </summary>
        public static string RepetitionWindow {
            get {
                return ResourceManager.GetString("RepetitionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при обработването на заявката. Провете дали залата е свободна..
        /// </summary>
        public static string RequestFailed {
            get {
                return ResourceManager.GetString("RequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявката е обработена успешно..
        /// </summary>
        public static string RequestSucceeded {
            get {
                return ResourceManager.GetString("RequestSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за резервацията.
        /// </summary>
        public static string ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля изберете зала....
        /// </summary>
        public static string SelectHall {
            get {
                return ResourceManager.GetString("SelectHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to резервация.
        /// </summary>
        public static string SingleReservation {
            get {
                return ResourceManager.GetString("SingleReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование на събитието.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
    }
}
