//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възложител.
        /// </summary>
        internal static string Assignor {
            get {
                return ResourceManager.GetString("Assignor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начален час.
        /// </summary>
        internal static string BeginsOn {
            get {
                return ResourceManager.GetString("BeginsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчисти.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-майл.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краен час.
        /// </summary>
        internal static string EndsOn {
            get {
                return ResourceManager.GetString("EndsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужна ли е мултимедийна / озвучителна техника?.
        /// </summary>
        internal static string IsEquipmentRequired {
            get {
                return ResourceManager.GetString("IsEquipmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to резервации.
        /// </summary>
        internal static string MultipleReservations {
            get {
                return ResourceManager.GetString("MultipleReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никога.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова резервация.
        /// </summary>
        internal static string NewReservation {
            get {
                return ResourceManager.GetString("NewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма направени резервации..
        /// </summary>
        internal static string NoReservations {
            get {
                return ResourceManager.GetString("NoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лице за контакт.
        /// </summary>
        internal static string PointOfContact {
            get {
                return ResourceManager.GetString("PointOfContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтаряемост.
        /// </summary>
        internal static string RepetitionPolicy {
            get {
                return ResourceManager.GetString("RepetitionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След брой повторения.
        /// </summary>
        internal static string RepetitionsCount {
            get {
                return ResourceManager.GetString("RepetitionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to През колко седмици.
        /// </summary>
        internal static string RepetitionWindow {
            get {
                return ResourceManager.GetString("RepetitionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за резервацията.
        /// </summary>
        internal static string ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to резервация.
        /// </summary>
        internal static string SingleReservation {
            get {
                return ResourceManager.GetString("SingleReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование на събитието.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
